export {
  getCategoryById,
  getFavoriteCategoriesForPokemon,
  getFavoriteItemsForPokemon,
  getHabitatConflicts,
  getHabitatCoverageBreakdown,
  getHabitatFitItems,
  getItemById,
  getItemsForFavoriteCategory,
  getBestHabitatsForTeam,
  getMatchingHabitatTraitsAll,
  getPokemonByFavoriteCategory,
  getPokemonForItem,
  getRecommendedCategoriesForHabitat,
  getRecommendedCategories,
  getRecommendedItemsForHabitat,
  getRecommendedItems,
  getSharedFavoriteCategories,
  getSharedFavoriteCategoriesAny,
  getSharedHabitats,
} from "../domain/selectors";
