export const SCORE_WEIGHTS = {
  SHARED_FAVORITE_PER_CATEGORY: 8,
  MATCHING_HABITAT_TRAIT: 4,
  CONFLICTING_HABITAT_TRAIT: -6,
  SAME_SPECIALTY: 1,
  DIFFERENT_SPECIALTY: 0,
  ALL_TEAM_SHARED_FAVORITE_BONUS: 6,
  ALL_TEAM_SHARED_HABITAT_BONUS: 4,
  ITEM_COVERAGE_PER_MATCHED_POKEMON: 3,
  CRAFTABLE_ITEM_BONUS: 1,
} as const;
